spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver


api:
  access:
    key: M2FiZjI2NTItYTk1OC00NTQ0LThlZmYtZDgwMjYzNzJkY2U5OmY1MmUzYWI0NTcyZDRmYjk5ZTc3N2ViNjI5ZTZiZmNm
  authentication:
    input: direct:authenticationInput
    output: direct:authenticationOutput
    endpoint: https://developers.lingvolive.com/api/v1/authenticate?bridgeEndpoint=true
  translation:
    article:
      input: direct:translationArticleInput
      endpoint: https://developers.lingvolive.com/api/v1/Article?bridgeEndpoint=true
    minicard:
      endpoint: https://developers.lingvolive.com/api/v1/Minicard?bridgeEndpoint=true
      output: direct:translationMinicardOutput
      input: direct:translationMinicardInput
    audio:
      endpoint: https://developers.lingvolive.com/api/v1/Sound?bridgeEndpoint=true
      output: direct:translationAudioOutput
      input: direct:translationAudioInput
      fileOutput: file:audio
---
spring:
  profiles:
    active: test

api:
  authentication:
    output: mock:authenticationOutput